### ISSUE TITLE
Agregar winston parte 2

### ISSUE THREAD

**Issue by Mitzisc** [Mitzisc/-fish-project#4]
Realizar la solución a winston con el ejemplo que se ha visto en clase

**Comment by CesarRomeroRuiz** [comment]
+Se movio un import al comienzo
+Se importaron mas componentes para crear el formato
+Añaden formatos de consola y salida de archivos log
+Creacion de objetos de configuracion info,warn,error,console
+Creacion de la instancia del logger
+Manejo de un stream de entrada
+Se agrega export default logger
